### ISSUE TITLE
Adjust uid of www-data user in php7-web

### ISSUE THREAD

**Issue by woodt** [GetDKAN/dkan-docker#13]
A running web container can create new files (e.g., in src/site/files/google_tag.)  These files will be owned by the Apache user (www-data.)  Unfortunately, Jenkins (for example) runs as a user that doesn't have permission to remove those files, which causes problems in cleaning up workspaces.

**Comment by erogray** [comment]
Done via https://app.zenhub.com/workspace/o/getdkan/dkan-docker/issues/14
