### ISSUE TITLE
Update to PHP 7.3

### ISSUE THREAD

**Issue by thierrydallacroce** [GetDKAN/dkan-docker#21]
#20 talks about a new repo but I see no mention of updating PHP. Currently the versions of PHP hardcoded in Dockerfiles are 7.1 in php7 and 7.2 in php72.

According to [PHP.net](https://www.php.net/supported-versions.php), 7.1 is no longer supported. Also, 7.2 is no longer in active support, only security support and that ends in Nov 2020.

Also, we’re on the cusp of Drupal 9 being released, 2 days from today and it will require at least php 7.3 according to [this page on D.O](https://www.drupal.org/docs/understanding-drupal/how-drupal-9-is-made-and-what-is-included/environment-requirements-of).

**Comment by dasumner** [comment]
There was some other discussion about this already having been done.  I need to verify with @dharizza and others to make sure this is still an open item.

**Comment by dharizza** [comment]
I can confirm we've been running PHP 7.3 for a while now.
